<?php

use App\School;
use App\faculty;
use App\Metier;
use App\Serie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetierTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $metier = [
           
            ['chercheur','Ingénieur en Génie mécanique','Ingénieur en Construction','Technicien réseau','Analyse de la donnée','Conseiler(ère) clientèle','Développeur'],
            ['Enseignant(e)','chercheur','Interprétariat et traducteur','Journalistes'],
            ['Enseignant(e)',' chercheur','Medecin','Officines de pharmacie'],
            ['Responsable de gestion administrative','Analyste financier'],
            ['Avocat','Majistrat','Agent Immobilier'],
            ['Enseignant(e)','chercheur'],
            ['Ingénieur agronome'],
            ['Commercant(e)','Opérateur de fabrication','Domoticien','Expert en sécurité informatique'],
            ['Enseignant(e)'],
            ['Réalisateur','Scénariste'],
            ['Promoteur des PME','Enseignant(e) ',' chercheur'],
            ['Commercant(e)'],
            ['Responsable de gestion administrative','Analyste financier'],
            ['Enseignant(e)','Responsable de gestion administrative','Analyste financier'],
            ['Avocat','Majistrat'],
            ['Ingénieur agronome'],
            ['Commercant(e)','Enseignant(e)','Opérateur de fabrication','Domoticien','Expert en sécurité informatique'],
            ['Réalisateur','Scénariste'],
            ['Enseignant(e)'],
            ['chercheur','Ingénieur en Génie mécanique','Ingénieur en Construction','Technicien réseau','Analyse de la donnée','Conseiler(ère) clientèle','Développeur'],
            ['Medecin','chercheur'],
            ['Enseignant(e)','chercheur'],
            ['Enseignant(e)',' chercheur','Medecin','Officines de pharmacie'],
            ['Enseignant(e)'],
            ['Avocat','Majistrat'],
            ['Responsable de gestion administrative','Analyste financier'],
            ['chercheur'],
            ['Avocat','Majistrat'],
            ['Technicien réseau','Analyse de la donnée','Développeur'],
            ['Enseignant(e)'],
            ['Commercant(e)','Technicien réseau','Opérateur de fabrication','Domoticien','Expert en sécurité informatique','Développeur'],
            ['Commercant(e)','Chef Comptable','Domoticien','Développeur'],
            ['Commercant(e)','Chef Comptable','Domoticien',],
            ['Secrétaire de Direction','Chef Comptable'],
            ['Domoticien','Expert en sécurité informatique','Développeur'],
            ['Ingénieur agronome','Commercant(e)','Enseignant(e)'],
            ['Commercant(e)','Technicien réseau','Chef Comptable','Développeur'],
            ['Enseignant(e)','Réalisateur','Scénariste'],
            ['chercheur','Ingénieur en Génie mécanique','Réalisateur'],
            ['Secrétaire de Direction','Chef Comptable','Commercant(e)'],
            ['Secrétaire de Direction','Chef Comptable','Commercant(e)','Réalisateur'],
            ['Secrétaire de Direction','Chef Comptable','Commercant(e)'],
            ['Secrétaire de Direction','Chef Comptable','Commercant(e)'],
        ];
        $BAC = [
            ['BAC C','BAC D','BAC E','BAC BT'],
            ['BAC A','BAC C','BAC D',],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E'],
            ['BAC C','BAC D','BAC E'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT'],
            ['BAC C','BAC D','BAC E'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC A'],
            ['BAC C'],
            ['BAC C'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC A'],
        ];
        $BAC_M = [
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC A','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
            ['BAC C','BAC D','BAC E','BAC BT','BAC F'],
        ];
        // $MATIERES = [
        //     ['Mathématique','Analyse Logique'],
        //     ['Physique','Mathématique'],
        //     ['Physique','Mathématique'],
        //     ['Physique','Mathématique'],
        //     ['Mathématique','Informatique'],
        //     ['Chimie','Mathématique'],
        //     ['Physique','Mathématique'],
        //     ['Hygiène'],
        //     ['langue francaise','langue anglaise'],
        //     ['Francais','Anglais','Géographie'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Philosophie'],
        //     ['Francais','Anglais','Histoire'],
        //     ['Francais','Anglais','Histoire','littérature'],
        //     ['Francais','Anglais','Francais'],
        //     ['Francais','Anglais','Histoire'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Mathématique','Francais'],
        //     ['Mathématique'],
        //     ['Francais','Anglais','Francais'],
        //     ['Francais','Anglais','Francais'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Chimie'],
        //     ['Francais','Anglais','Chimie'],
        //     ['Francais','Anglais','Mathématique','Informatique'],
        //     ['Francais','Anglais','Physique'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Informatique'],
        //     ['Francais','Anglais','Informatique'],
        //     ['Francais','Anglais','Informatique'],
        //     ['Francais','Anglais','ESF'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Informatique'],
        //     ['Francais','Anglais'],
        //     ['Physique','Francais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais'],
        //     ['Science de la vie et de la terre'],
        //     ['Chimie'],
        //     ['Geographie'],
        //     ['Francais','Mathématique','Informatique'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Histoire','Francais'],
        //     ['Francais','Geographie'],
        //     ['Francais','Histoire'],
        //     ['Francais','Anglais'],
        //     ['Philosophie'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Mathématique'],
        //     ['Francais','Anglais','Informatique'],
        //     ['Francais','Informatique'],
        //     ['Francais','Informatique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Anglais'],
        //     ['Chimie'],
        //     ['Geographie'],
        //     ['Histoire'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Anglais','Philosophie'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Mathématique','Informatique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Physique','Mathématique','Informatique'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Physique','Mathématique','Informatique'],
        //     ['Chimie'],
        //     ['Chimie'],
        //     ['Chimie'],
        //     ['Francais','Physique','Mathématique'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Biochimie'],
        //     ['Anglais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais','Anglais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Philosophie'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Mathématique'],
        //     ['Francais','Mathématique','Physique'],
        //     ['Chimie'],
        //     ['Francais','Science de la vie et de la terre'],
        //     ['Geographie'],
        //     ['Francais','Anglais'],
        //     ['Francais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Philosophie'],
        //     ['Histoire'],
        //     ['Francais','Mathématique','Informatique'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Mathematique'],
        //     ['Francais'],
        //     ['Francais','Mathematique'],
        //     ['Francais'],
        //     ['Histoire'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Anglais'],
        //     ['Francais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Anglais','Histoire'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Anglais'],
        //     ['Francais'],
        //     ['Francais'],
        //     ['Francais','Histoire'],
        //     ['Francais','Histoire'],
        //     ['Francais','Histoire'],
        //     ['Francais','Histoire'],
        //     ['Francais','Histoire'],
        //     ['Francais'],
        //     ['Francais','Anglais'],
        //     ['Francais','Mathematique'],
        //     ['Francais','Anglais','Philosophie'],
        //     ['Francais','Mathematique'],
            //204

        // ];
        $schools = School::all();
        foreach ($schools as $key1 => $school){
           foreach ($metier as $key2 => $value){
            foreach ($value as $val){
                    if ($key1 == $key2) {
                        $result = DB::table('metiers')->select('id')->where('name' , $val)->first();
                        $school->metiers()->attach($result);
                }
                }
           }
        }
        foreach ($schools as $key1 => $school){
            foreach ($BAC as $key2 => $value){
             foreach ($value as $val){
                    if ($key1 == $key2) {
                        $result = DB::table('series')->select('id')->where('name' , $val)->first();
                        $school->series()->attach($result);
                   }
                 }
            }
         }
         $metiers = Metier::all();
        foreach ($metiers as $key1 => $metier){
           foreach ($BAC_M as $key2 => $BAC){
            foreach ($BAC as $val){
                    if ($key1 == $key2) {
                        $result = DB::table('series')->select('id')->where('name' , $val)->first();
                        $metier->series()->attach($result);
                }
                }
           }
        }
    }
}
